# Generated by Django 4.1.7 on 2023-03-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='largura',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
