# Generated by Django 4.1.7 on 2023-04-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_item_altura_item_largura'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente_aceitou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pago',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
