# Generated by Django 4.1.7 on 2023-04-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_orcamento_cliente_aceitou_orcamento_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamentos.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente_aceitou',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
